const puzzles = {
    animals: [
        { word: "CAT", clue: "House pet that meows" },
        { word: "DOG", clue: "Man's best friend" },
        { word: "BEAR", clue: "Large forest mammal" },
        { word: "WOLF", clue: "Pack hunting canine" },
        { word: "DEER", clue: "Antlered forest animal" },
        { word: "FISH", clue: "Water-dwelling creature" },
        { word: "BIRD", clue: "Flying creature with feathers" },
        { word: "MOUSE", clue: "Small rodent" },
        { word: "HORSE", clue: "Domesticated riding animal" },
        { word: "SNAKE", clue: "Slithering reptile" },
        { word: "TIGER", clue: "Striped big cat" },
        { word: "EAGLE", clue: "National bird of America" },
        { word: "ZEBRA", clue: "Striped African horse" },
        { word: "RABBIT", clue: "Hopping garden visitor" },
        { word: "TURTLE", clue: "Reptile with a shell" },
        { word: "MONKEY", clue: "Primate that swings from trees" },
        { word: "DOLPHIN", clue: "Intelligent marine mammal" },
        { word: "PENGUIN", clue: "Flightless Antarctic bird" },
        { word: "GIRAFFE", clue: "Tallest animal in the world" },
        { word: "ELEPHANT", clue: "Largest land animal" },
        { word: "KANGAROO", clue: "Hopping Australian marsupial" },
        { word: "LION", clue: "King of the jungle" },
        { word: "SHARK", clue: "Ocean predator with sharp teeth" },
        { word: "WHALE", clue: "Largest mammal in the ocean" },
        { word: "COW", clue: "Farm animal that gives milk" },
        { word: "PIG", clue: "Farm animal that rolls in mud" },
        { word: "CHICKEN", clue: "Farm bird that lays eggs" },
        { word: "FROG", clue: "Amphibian that croaks" },
        { word: "SPIDER", clue: "Eight-legged web spinner" },
        { word: "ANT", clue: "Hard-working insect" }
    ],
    
    food: [
        { word: "PIZZA", clue: "Italian flatbread with toppings" },
        { word: "BREAD", clue: "Baked staple food" },
        { word: "APPLE", clue: "Red or green fruit" },
        { word: "CHEESE", clue: "Dairy product from milk" },
        { word: "PASTA", clue: "Italian noodle dish" },
        { word: "RICE", clue: "Grain staple food" },
        { word: "MEAT", clue: "Animal protein" },
        { word: "FISH", clue: "Seafood protein" },
        { word: "SOUP", clue: "Liquid meal" },
        { word: "SALAD", clue: "Mixed greens dish" },
        { word: "CAKE", clue: "Sweet dessert" },
        { word: "COOKIE", clue: "Sweet baked treat" },
        { word: "BURGER", clue: "Sandwich with patty" },
        { word: "CHICKEN", clue: "Poultry meat" },
        { word: "POTATO", clue: "Starchy vegetable" },
        { word: "TOMATO", clue: "Red garden fruit" },
        { word: "BANANA", clue: "Yellow curved fruit" },
        { word: "ORANGE", clue: "Citrus fruit" },
        { word: "SANDWICH", clue: "Food between bread slices" },
        { word: "CHOCOLATE", clue: "Sweet cocoa treat" },
        { word: "SPAGHETTI", clue: "Long thin pasta" },
        { word: "PANCAKE", clue: "Flat breakfast cake" },
        { word: "WAFFLE", clue: "Grid-patterned breakfast food" },
        { word: "DONUT", clue: "Fried sweet ring" },
        { word: "MUFFIN", clue: "Small cake" },
        { word: "BAGEL", clue: "Ring-shaped bread" },
        { word: "STEAK", clue: "Grilled beef cut" },
        { word: "SALMON", clue: "Pink fish" },
        { word: "TACO", clue: "Mexican folded food" },
        { word: "YOGURT", clue: "Cultured dairy product" }
    ],
    
    sports: [
        { word: "BALL", clue: "Round sports object" },
        { word: "GOAL", clue: "Sports scoring target" },
        { word: "TEAM", clue: "Group of players" },
        { word: "GAME", clue: "Sports competition" },
        { word: "RACE", clue: "Speed competition" },
        { word: "SOCCER", clue: "Football played with feet" },
        { word: "TENNIS", clue: "Racket sport" },
        { word: "GOLF", clue: "Club and ball sport" },
        { word: "BOXING", clue: "Fighting sport" },
        { word: "HOCKEY", clue: "Ice sport with sticks" },
        { word: "RUGBY", clue: "Rough ball sport" },
        { word: "CRICKET", clue: "British bat sport" },
        { word: "BASEBALL", clue: "American bat sport" },
        { word: "FOOTBALL", clue: "American tackle sport" },
        { word: "SWIMMING", clue: "Water sport" },
        { word: "RUNNING", clue: "Track sport" },
        { word: "CYCLING", clue: "Bike sport" },
        { word: "SKIING", clue: "Snow sport" },
        { word: "SURFING", clue: "Wave riding sport" },
        { word: "BOWLING", clue: "Pin knocking sport" },
        { word: "ARCHERY", clue: "Bow and arrow sport" },
        { word: "FENCING", clue: "Sword sport" },
        { word: "KARATE", clue: "Martial art" },
        { word: "JUDO", clue: "Japanese martial art" },
        { word: "YOGA", clue: "Flexibility practice" },
        { word: "DANCE", clue: "Movement art" },
        { word: "HIKING", clue: "Trail walking" },
        { word: "FISHING", clue: "Catching fish sport" },
        { word: "CAMPING", clue: "Outdoor sleeping" },
        { word: "CLIMBING", clue: "Ascending sport" }
    ],
    
    colors: [
        { word: "RED", clue: "Color of fire" },
        { word: "BLUE", clue: "Color of sky" },
        { word: "GREEN", clue: "Color of grass" },
        { word: "YELLOW", clue: "Color of sun" },
        { word: "ORANGE", clue: "Color of fruit" },
        { word: "PURPLE", clue: "Color of grapes" },
        { word: "PINK", clue: "Light red color" },
        { word: "BROWN", clue: "Color of earth" },
        { word: "BLACK", clue: "Darkest color" },
        { word: "WHITE", clue: "Lightest color" },
        { word: "GRAY", clue: "Mix of black and white" },
        { word: "SILVER", clue: "Metallic color" },
        { word: "GOLD", clue: "Precious metal color" },
        { word: "BEIGE", clue: "Light brown color" },
        { word: "NAVY", clue: "Dark blue color" },
        { word: "LIME", clue: "Bright green color" },
        { word: "CORAL", clue: "Pinkish orange color" },
        { word: "VIOLET", clue: "Purple flower color" },
        { word: "INDIGO", clue: "Deep blue color" },
        { word: "CRIMSON", clue: "Deep red color" },
        { word: "EMERALD", clue: "Bright green color" },
        { word: "SAPPHIRE", clue: "Blue gemstone color" },
        { word: "RUBY", clue: "Red gemstone color" },
        { word: "AMBER", clue: "Golden yellow color" },
        { word: "BRONZE", clue: "Brown metal color" },
        { word: "COPPER", clue: "Reddish metal color" },
        { word: "CREAM", clue: "Off-white color" },
        { word: "IVORY", clue: "Pale yellow color" },
        { word: "SALMON", clue: "Pinkish orange color" },
        { word: "TEAL", clue: "Blue-green color" }
    ],
    
    weather: [
        { word: "SUN", clue: "Bright star" },
        { word: "RAIN", clue: "Water from clouds" },
        { word: "WIND", clue: "Moving air" },
        { word: "SNOW", clue: "Frozen precipitation" },
        { word: "FOG", clue: "Thick mist" },
        { word: "CLOUD", clue: "Sky water vapor" },
        { word: "STORM", clue: "Violent weather" },
        { word: "HAIL", clue: "Ice pellets" },
        { word: "MIST", clue: "Light fog" },
        { word: "FROST", clue: "Ice crystals" },
        { word: "HEAT", clue: "Hot temperature" },
        { word: "COLD", clue: "Low temperature" },
        { word: "WARM", clue: "Mild temperature" },
        { word: "COOL", clue: "Slightly cold" },
        { word: "HUMID", clue: "Moist air" },
        { word: "SUNNY", clue: "Bright weather" },
        { word: "CLOUDY", clue: "Overcast sky" },
        { word: "WINDY", clue: "Breezy conditions" },
        { word: "RAINY", clue: "Wet weather" },
        { word: "SNOWY", clue: "White weather" },
        { word: "THUNDER", clue: "Storm sound" },
        { word: "LIGHTNING", clue: "Electric flash" },
        { word: "RAINBOW", clue: "Colorful arc" },
        { word: "TORNADO", clue: "Spinning storm" },
        { word: "HURRICANE", clue: "Major storm" },
        { word: "BLIZZARD", clue: "Snow storm" },
        { word: "DRIZZLE", clue: "Light rain" },
        { word: "SHOWER", clue: "Brief rain" },
        { word: "BREEZE", clue: "Light wind" },
        { word: "GALE", clue: "Strong wind" }
    ],
    
    music: [
        { word: "SONG", clue: "Musical composition" },
        { word: "BEAT", clue: "Musical rhythm" },
        { word: "TUNE", clue: "Musical melody" },
        { word: "PIANO", clue: "Keyboard instrument" },
        { word: "GUITAR", clue: "Stringed instrument" },
        { word: "DRUMS", clue: "Percussion instruments" },
        { word: "VIOLIN", clue: "String instrument with bow" },
        { word: "FLUTE", clue: "Wind instrument" },
        { word: "SINGER", clue: "Vocal performer" },
        { word: "BAND", clue: "Musical group" },
        { word: "ALBUM", clue: "Collection of songs" },
        { word: "CONCERT", clue: "Live performance" },
        { word: "MELODY", clue: "Musical tune" },
        { word: "HARMONY", clue: "Musical agreement" },
        { word: "RHYTHM", clue: "Musical timing" },
        { word: "CLASSICAL", clue: "Formal music style" },
        { word: "JAZZ", clue: "American music style" },
        { word: "ROCK", clue: "Popular music style" },
        { word: "BLUES", clue: "Soulful music style" },
        { word: "COUNTRY", clue: "Rural music style" },
        { word: "DANCE", clue: "Movement music" },
        { word: "OPERA", clue: "Dramatic singing" },
        { word: "CHORUS", clue: "Group singing" },
        { word: "SOLO", clue: "Single performer" },
        { word: "DUET", clue: "Two performers" },
        { word: "QUARTET", clue: "Four performers" },
        { word: "TRUMPET", clue: "Brass instrument" },
        { word: "SAXOPHONE", clue: "Jazz instrument" },
        { word: "ORCHESTRA", clue: "Large musical group" },
        { word: "SYMPHONY", clue: "Long musical work" }
    ],
    
    transportation: [
        { word: "CAR", clue: "Personal vehicle" },
        { word: "BUS", clue: "Public transport" },
        { word: "TRAIN", clue: "Railway vehicle" },
        { word: "PLANE", clue: "Flying vehicle" },
        { word: "BOAT", clue: "Water vehicle" },
        { word: "BIKE", clue: "Two-wheeled vehicle" },
        { word: "TRUCK", clue: "Large cargo vehicle" },
        { word: "TAXI", clue: "Hire vehicle" },
        { word: "SUBWAY", clue: "Underground train" },
        { word: "FERRY", clue: "Water crossing vehicle" },
        { word: "HELICOPTER", clue: "Rotating wing aircraft" },
        { word: "MOTORCYCLE", clue: "Motorized bike" },
        { word: "SCOOTER", clue: "Small bike" },
        { word: "SKATEBOARD", clue: "Wheeled board" },
        { word: "ROLLERBLADE", clue: "Wheeled boot" },
        { word: "SHIP", clue: "Large water vessel" },
        { word: "YACHT", clue: "Luxury boat" },
        { word: "CANOE", clue: "Paddle boat" },
        { word: "KAYAK", clue: "Small paddle boat" },
        { word: "ROCKET", clue: "Space vehicle" },
        { word: "BALLOON", clue: "Hot air transport" },
        { word: "GLIDER", clue: "Engineless aircraft" },
        { word: "WAGON", clue: "Pulled vehicle" },
        { word: "SLEIGH", clue: "Snow vehicle" },
        { word: "SLED", clue: "Sliding vehicle" },
        { word: "TROLLEY", clue: "Street car" },
        { word: "TRAM", clue: "City rail vehicle" },
        { word: "RICKSHAW", clue: "Pulled cart" },
        { word: "AMBULANCE", clue: "Emergency vehicle" },
        { word: "FIRETRUCK", clue: "Emergency vehicle" }
    ],
    
    nature: [
        { word: "TREE", clue: "Large woody plant" },
        { word: "FLOWER", clue: "Plant bloom" },
        { word: "GRASS", clue: "Ground cover" },
        { word: "ROCK", clue: "Stone formation" },
        { word: "WATER", clue: "Clear liquid" },
        { word: "EARTH", clue: "Ground soil" },
        { word: "FIRE", clue: "Burning flame" },
        { word: "RIVER", clue: "Flowing water" },
        { word: "LAKE", clue: "Large water body" },
        { word: "OCEAN", clue: "Vast water body" },
        { word: "MOUNTAIN", clue: "High land formation" },
        { word: "VALLEY", clue: "Low land between hills" },
        { word: "FOREST", clue: "Dense tree area" },
        { word: "DESERT", clue: "Dry sandy area" },
        { word: "BEACH", clue: "Sandy shore" },
        { word: "ISLAND", clue: "Land surrounded by water" },
        { word: "CAVE", clue: "Underground chamber" },
        { word: "CLIFF", clue: "Steep rock face" },
        { word: "WATERFALL", clue: "Falling water" },
        { word: "RAINBOW", clue: "Colorful arc" },
        { word: "SUNRISE", clue: "Dawn light" },
        { word: "SUNSET", clue: "Evening light" },
        { word: "MEADOW", clue: "Grassy field" },
        { word: "POND", clue: "Small water body" },
        { word: "STREAM", clue: "Small flowing water" },
        { word: "GLACIER", clue: "Moving ice mass" },
        { word: "VOLCANO", clue: "Mountain with lava" },
        { word: "CANYON", clue: "Deep valley" },
        { word: "PLAIN", clue: "Flat land area" },
        { word: "JUNGLE", clue: "Dense tropical forest" }
    ],
    
    technology: [
        { word: "PHONE", clue: "Communication device" },
        { word: "COMPUTER", clue: "Electronic machine" },
        { word: "TABLET", clue: "Touch screen device" },
        { word: "LAPTOP", clue: "Portable computer" },
        { word: "MOUSE", clue: "Computer pointer" },
        { word: "KEYBOARD", clue: "Input device" },
        { word: "SCREEN", clue: "Display surface" },
        { word: "CAMERA", clue: "Photo device" },
        { word: "SPEAKER", clue: "Audio output" },
        { word: "MICROPHONE", clue: "Audio input" },
        { word: "HEADPHONES", clue: "Personal audio" },
        { word: "PRINTER", clue: "Document output" },
        { word: "SCANNER", clue: "Document input" },
        { word: "ROUTER", clue: "Network device" },
        { word: "MODEM", clue: "Internet connection" },
        { word: "CABLE", clue: "Connection wire" },
        { word: "BATTERY", clue: "Power source" },
        { word: "CHARGER", clue: "Power device" },
        { word: "MEMORY", clue: "Storage component" },
        { word: "PROCESSOR", clue: "Computing chip" },
        { word: "SOFTWARE", clue: "Computer programs" },
        { word: "HARDWARE", clue: "Physical components" },
        { word: "INTERNET", clue: "Global network" },
        { word: "WEBSITE", clue: "Online location" },
        { word: "EMAIL", clue: "Electronic mail" },
        { word: "ROBOT", clue: "Automated machine" },
        { word: "DRONE", clue: "Flying robot" },
        { word: "SMARTWATCH", clue: "Wrist computer" },
        { word: "TELEVISION", clue: "Broadcast receiver" },
        { word: "RADIO", clue: "Audio receiver" }
    ],
    
    clothing: [
        { word: "SHIRT", clue: "Upper body garment" },
        { word: "PANTS", clue: "Lower body garment" },
        { word: "DRESS", clue: "One-piece garment" },
        { word: "SHOES", clue: "Foot coverings" },
        { word: "SOCKS", clue: "Foot garments" },
        { word: "HAT", clue: "Head covering" },
        { word: "COAT", clue: "Outer garment" },
        { word: "JACKET", clue: "Light outer wear" },
        { word: "SWEATER", clue: "Warm knitted top" },
        { word: "SHORTS", clue: "Short pants" },
        { word: "SKIRT", clue: "Lower body garment" },
        { word: "BLOUSE", clue: "Women's shirt" },
        { word: "JEANS", clue: "Denim pants" },
        { word: "SNEAKERS", clue: "Athletic shoes" },
        { word: "BOOTS", clue: "High shoes" },
        { word: "SANDALS", clue: "Open shoes" },
        { word: "GLOVES", clue: "Hand coverings" },
        { word: "SCARF", clue: "Neck covering" },
        { word: "BELT", clue: "Waist accessory" },
        { word: "TIE", clue: "Neck accessory" },
        { word: "SUIT", clue: "Formal outfit" },
        { word: "UNIFORM", clue: "Standard clothing" },
        { word: "PAJAMAS", clue: "Sleep clothes" },
        { word: "SWIMSUIT", clue: "Water clothing" },
        { word: "UNDERWEAR", clue: "Hidden garment" },
        { word: "CARDIGAN", clue: "Button sweater" },
        { word: "HOODIE", clue: "Hooded sweatshirt" },
        { word: "TSHIRT", clue: "Casual shirt" },
        { word: "POLO", clue: "Collared shirt" },
        { word: "APRON", clue: "Protective garment" }
    ],
    
    school: [
        { word: "BOOK", clue: "Reading material" },
        { word: "PEN", clue: "Writing tool" },
        { word: "PAPER", clue: "Writing surface" },
        { word: "DESK", clue: "Study furniture" },
        { word: "CHAIR", clue: "Seating furniture" },
        { word: "TEACHER", clue: "Instructor" },
        { word: "STUDENT", clue: "Learner" },
        { word: "CLASS", clue: "Learning group" },
        { word: "LESSON", clue: "Teaching session" },
        { word: "HOMEWORK", clue: "Study assignment" },
        { word: "TEST", clue: "Assessment" },
        { word: "EXAM", clue: "Major test" },
        { word: "GRADE", clue: "Score mark" },
        { word: "REPORT", clue: "Progress card" },
        { word: "LIBRARY", clue: "Book collection" },
        { word: "COMPUTER", clue: "Electronic device" },
        { word: "BOARD", clue: "Writing surface" },
        { word: "CHALK", clue: "Writing stick" },
        { word: "ERASER", clue: "Mistake remover" },
        { word: "RULER", clue: "Measuring tool" },
        { word: "CALCULATOR", clue: "Math device" },
        { word: "NOTEBOOK", clue: "Writing pad" },
        { word: "BACKPACK", clue: "School bag" },
        { word: "PENCIL", clue: "Writing tool" },
        { word: "CRAYON", clue: "Coloring stick" },
        { word: "MARKER", clue: "Coloring pen" },
        { word: "SCISSORS", clue: "Cutting tool" },
        { word: "GLUE", clue: "Adhesive" },
        { word: "STAPLER", clue: "Fastening tool" },
        { word: "FOLDER", clue: "Paper organizer" }
    ],
    
    home: [
        { word: "HOUSE", clue: "Living structure" },
        { word: "ROOM", clue: "Indoor space" },
        { word: "DOOR", clue: "Room entrance" },
        { word: "WINDOW", clue: "Glass opening" },
        { word: "WALL", clue: "Room boundary" },
        { word: "FLOOR", clue: "Walking surface" },
        { word: "CEILING", clue: "Room top" },
        { word: "KITCHEN", clue: "Cooking room" },
        { word: "BEDROOM", clue: "Sleeping room" },
        { word: "BATHROOM", clue: "Washing room" },
        { word: "LIVING", clue: "Main room" },
        { word: "DINING", clue: "Eating room" },
        { word: "GARAGE", clue: "Car storage" },
        { word: "GARDEN", clue: "Plant area" },
        { word: "YARD", clue: "Outside space" },
        { word: "STAIRS", clue: "Level changer" },
        { word: "BASEMENT", clue: "Underground room" },
        { word: "ATTIC", clue: "Top storage" },
        { word: "CLOSET", clue: "Storage space" },
        { word: "CABINET", clue: "Storage unit" },
        { word: "DRAWER", clue: "Sliding storage" },
        { word: "SHELF", clue: "Storage board" },
        { word: "TABLE", clue: "Flat surface" },
        { word: "CHAIR", clue: "Seating furniture" },
        { word: "SOFA", clue: "Soft seating" },
        { word: "BED", clue: "Sleeping furniture" },
        { word: "MIRROR", clue: "Reflection glass" },
        { word: "LAMP", clue: "Light source" },
        { word: "CARPET", clue: "Floor covering" },
        { word: "CURTAIN", clue: "Window covering" }
    ],
    
    body: [
        { word: "HEAD", clue: "Top body part" },
        { word: "FACE", clue: "Front of head" },
        { word: "EYE", clue: "Vision organ" },
        { word: "NOSE", clue: "Smell organ" },
        { word: "MOUTH", clue: "Eating opening" },
        { word: "EAR", clue: "Hearing organ" },
        { word: "NECK", clue: "Head connector" },
        { word: "SHOULDER", clue: "Arm connector" },
        { word: "ARM", clue: "Upper limb" },
        { word: "HAND", clue: "Grasping part" },
        { word: "FINGER", clue: "Hand digit" },
        { word: "THUMB", clue: "Opposable digit" },
        { word: "CHEST", clue: "Upper torso" },
        { word: "BACK", clue: "Rear torso" },
        { word: "STOMACH", clue: "Belly area" },
        { word: "WAIST", clue: "Middle section" },
        { word: "HIP", clue: "Side joint" },
        { word: "LEG", clue: "Lower limb" },
        { word: "KNEE", clue: "Leg joint" },
        { word: "FOOT", clue: "Walking part" },
        { word: "TOE", clue: "Foot digit" },
        { word: "ANKLE", clue: "Foot joint" },
        { word: "ELBOW", clue: "Arm joint" },
        { word: "WRIST", clue: "Hand joint" },
        { word: "SKIN", clue: "Body covering" },
        { word: "HAIR", clue: "Head covering" },
        { word: "TOOTH", clue: "Chewing part" },
        { word: "TONGUE", clue: "Taste organ" },
        { word: "BRAIN", clue: "Thinking organ" },
        { word: "HEART", clue: "Pumping organ" }
    ],
    
    jobs: [
        { word: "DOCTOR", clue: "Medical professional" },
        { word: "NURSE", clue: "Medical helper" },
        { word: "TEACHER", clue: "Education professional" },
        { word: "LAWYER", clue: "Legal professional" },
        { word: "PILOT", clue: "Aircraft operator" },
        { word: "CHEF", clue: "Kitchen professional" },
        { word: "ARTIST", clue: "Creative professional" },
        { word: "WRITER", clue: "Text creator" },
        { word: "SINGER", clue: "Vocal performer" },
        { word: "ACTOR", clue: "Performance artist" },
        { word: "BUILDER", clue: "Construction worker" },
        { word: "PLUMBER", clue: "Pipe specialist" },
        { word: "ELECTRICIAN", clue: "Wiring specialist" },
        { word: "MECHANIC", clue: "Repair specialist" },
        { word: "FARMER", clue: "Agricultural worker" },
        { word: "BAKER", clue: "Bread maker" },
        { word: "BARBER", clue: "Hair cutter" },
        { word: "DRIVER", clue: "Vehicle operator" },
        { word: "CASHIER", clue: "Payment handler" },
        { word: "WAITER", clue: "Food server" },
        { word: "CLEANER", clue: "Cleaning specialist" },
        { word: "GUARD", clue: "Security worker" },
        { word: "POLICE", clue: "Law enforcement" },
        { word: "FIREFIGHTER", clue: "Emergency responder" },
        { word: "SOLDIER", clue: "Military worker" },
        { word: "ENGINEER", clue: "Technical designer" },
        { word: "SCIENTIST", clue: "Research professional" },
        { word: "MANAGER", clue: "Business leader" },
        { word: "SALESPERSON", clue: "Selling specialist" },
        { word: "PROGRAMMER", clue: "Code writer" }
    ],
    
    tools: [
        { word: "HAMMER", clue: "Pounding tool" },
        { word: "SAW", clue: "Cutting tool" },
        { word: "DRILL", clue: "Hole making tool" },
        { word: "SCREWDRIVER", clue: "Screw turning tool" },
        { word: "WRENCH", clue: "Nut turning tool" },
        { word: "PLIERS", clue: "Gripping tool" },
        { word: "SCISSORS", clue: "Cutting tool" },
        { word: "KNIFE", clue: "Sharp cutting tool" },
        { word: "SPOON", clue: "Scooping tool" },
        { word: "FORK", clue: "Eating tool" },
        { word: "SHOVEL", clue: "Digging tool" },
        { word: "RAKE", clue: "Gathering tool" },
        { word: "BROOM", clue: "Sweeping tool" },
        { word: "MOP", clue: "Cleaning tool" },
        { word: "BUCKET", clue: "Carrying container" },
        { word: "LADDER", clue: "Climbing tool" },
        { word: "ROPE", clue: "Binding tool" },
        { word: "TAPE", clue: "Sticking tool" },
        { word: "GLUE", clue: "Adhesive tool" },
        { word: "BRUSH", clue: "Painting tool" },
        { word: "RULER", clue: "Measuring tool" },
        { word: "SCALE", clue: "Weighing tool" },
        { word: "LEVEL", clue: "Straightening tool" },
        { word: "CHISEL", clue: "Carving tool" },
        { word: "FILE", clue: "Smoothing tool" },
        { word: "SANDPAPER", clue: "Smoothing material" },
        { word: "NEEDLE", clue: "Sewing tool" },
        { word: "THREAD", clue: "Sewing material" },
        { word: "THIMBLE", clue: "Finger protector" },
        { word: "STAPLER", clue: "Fastening tool" }
    ],
    
    vegetables: [
        { word: "CARROT", clue: "Orange root vegetable" },
        { word: "POTATO", clue: "Starchy tuber" },
        { word: "ONION", clue: "Layered bulb vegetable" },
        { word: "TOMATO", clue: "Red fruit vegetable" },
        { word: "LETTUCE", clue: "Leafy green vegetable" },
        { word: "CABBAGE", clue: "Leafy head vegetable" },
        { word: "SPINACH", clue: "Iron-rich green" },
        { word: "BROCCOLI", clue: "Green tree vegetable" },
        { word: "CAULIFLOWER", clue: "White tree vegetable" },
        { word: "CELERY", clue: "Crunchy stalk vegetable" },
        { word: "CUCUMBER", clue: "Green cooling vegetable" },
        { word: "PEPPER", clue: "Bell vegetable" },
        { word: "CORN", clue: "Yellow kernel vegetable" },
        { word: "PEAS", clue: "Green pod vegetable" },
        { word: "BEANS", clue: "Protein-rich vegetable" },
        { word: "SQUASH", clue: "Gourd vegetable" },
        { word: "PUMPKIN", clue: "Orange gourd vegetable" },
        { word: "BEET", clue: "Red root vegetable" },
        { word: "RADISH", clue: "Spicy root vegetable" },
        { word: "TURNIP", clue: "White root vegetable" },
        { word: "PARSNIP", clue: "Cream root vegetable" },
        { word: "LEEK", clue: "Mild onion relative" },
        { word: "GARLIC", clue: "Pungent bulb" },
        { word: "GINGER", clue: "Spicy root" },
        { word: "MUSHROOM", clue: "Fungus vegetable" },
        { word: "ASPARAGUS", clue: "Spear vegetable" },
        { word: "ARTICHOKE", clue: "Thistle vegetable" },
        { word: "EGGPLANT", clue: "Purple vegetable" },
        { word: "ZUCCHINI", clue: "Green squash" },
        { word: "KALE", clue: "Curly green vegetable" }
    ],
    
    fruits: [
        { word: "APPLE", clue: "Red or green fruit" },
        { word: "BANANA", clue: "Yellow curved fruit" },
        { word: "ORANGE", clue: "Citrus fruit" },
        { word: "GRAPE", clue: "Cluster fruit" },
        { word: "LEMON", clue: "Sour citrus fruit" },
        { word: "LIME", clue: "Green citrus fruit" },
        { word: "CHERRY", clue: "Small red fruit" },
        { word: "PEACH", clue: "Fuzzy orange fruit" },
        { word: "PEAR", clue: "Teardrop fruit" },
        { word: "PLUM", clue: "Purple stone fruit" },
        { word: "STRAWBERRY", clue: "Red seeded fruit" },
        { word: "BLUEBERRY", clue: "Small blue fruit" },
        { word: "RASPBERRY", clue: "Red cluster fruit" },
        { word: "BLACKBERRY", clue: "Dark cluster fruit" },
        { word: "PINEAPPLE", clue: "Tropical spiky fruit" },
        { word: "MANGO", clue: "Tropical orange fruit" },
        { word: "PAPAYA", clue: "Tropical orange fruit" },
        { word: "KIWI", clue: "Fuzzy green fruit" },
        { word: "MELON", clue: "Large round fruit" },
        { word: "WATERMELON", clue: "Large green fruit" },
        { word: "CANTALOUPE", clue: "Orange melon" },
        { word: "HONEYDEW", clue: "Green melon" },
        { word: "AVOCADO", clue: "Green creamy fruit" },
        { word: "COCONUT", clue: "Tropical hard fruit" },
        { word: "POMEGRANATE", clue: "Seeded red fruit" },
        { word: "CRANBERRY", clue: "Tart red fruit" },
        { word: "APRICOT", clue: "Small orange fruit" },
        { word: "NECTARINE", clue: "Smooth peach" },
        { word: "GRAPEFRUIT", clue: "Large citrus fruit" },
        { word: "TANGERINE", clue: "Small orange citrus" }
    ],
    
    games: [
        { word: "CHESS", clue: "Strategic board game" },
        { word: "CHECKERS", clue: "Jump board game" },
        { word: "CARDS", clue: "Playing deck game" },
        { word: "DICE", clue: "Cube chance game" },
        { word: "PUZZLE", clue: "Piece fitting game" },
        { word: "BINGO", clue: "Number calling game" },
        { word: "DARTS", clue: "Target throwing game" },
        { word: "POOL", clue: "Cue stick game" },
        { word: "BOWLING", clue: "Pin rolling game" },
        { word: "GOLF", clue: "Hole target game" },
        { word: "TENNIS", clue: "Racket net game" },
        { word: "PING", clue: "Table tennis" },
        { word: "DOMINOES", clue: "Dot matching game" },
        { word: "SCRABBLE", clue: "Word building game" },
        { word: "MONOPOLY", clue: "Property board game" },
        { word: "CLUE", clue: "Mystery board game" },
        { word: "RISK", clue: "World conquest game" },
        { word: "TRIVIAL", clue: "Knowledge game" },
        { word: "YAHTZEE", clue: "Dice scoring game" },
        { word: "UNO", clue: "Color matching game" },
        { word: "POKER", clue: "Betting card game" },
        { word: "BLACKJACK", clue: "Twenty-one card game" },
        { word: "SOLITAIRE", clue: "Single player cards" },
        { word: "BRIDGE", clue: "Partnership card game" },
        { word: "RUMMY", clue: "Set making card game" },
        { word: "CHARADES", clue: "Acting guessing game" },
        { word: "PICTIONARY", clue: "Drawing guessing game" },
        { word: "TWISTER", clue: "Body position game" },
        { word: "JENGA", clue: "Block stacking game" },
        { word: "CONNECT", clue: "Four in a row game" }
    ],
    
    emotions: [
        { word: "HAPPY", clue: "Joyful feeling" },
        { word: "SAD", clue: "Sorrowful feeling" },
        { word: "ANGRY", clue: "Mad feeling" },
        { word: "SCARED", clue: "Frightened feeling" },
        { word: "EXCITED", clue: "Thrilled feeling" },
        { word: "CALM", clue: "Peaceful feeling" },
        { word: "NERVOUS", clue: "Anxious feeling" },
        { word: "PROUD", clue: "Accomplished feeling" },
        { word: "SILLY", clue: "Playful feeling" },
        { word: "TIRED", clue: "Exhausted feeling" },
        { word: "BORED", clue: "Uninterested feeling" },
        { word: "CURIOUS", clue: "Wondering feeling" },
        { word: "SURPRISED", clue: "Shocked feeling" },
        { word: "CONFUSED", clue: "Puzzled feeling" },
        { word: "JEALOUS", clue: "Envious feeling" },
        { word: "GRATEFUL", clue: "Thankful feeling" },
        { word: "LONELY", clue: "Isolated feeling" },
        { word: "HOPEFUL", clue: "Optimistic feeling" },
        { word: "WORRIED", clue: "Concerned feeling" },
        { word: "RELAXED", clue: "Comfortable feeling" },
        { word: "FRUSTRATED", clue: "Annoyed feeling" },
        { word: "DISAPPOINTED", clue: "Let down feeling" },
        { word: "EMBARRASSED", clue: "Ashamed feeling" },
        { word: "CONFIDENT", clue: "Self-assured feeling" },
        { word: "LOVING", clue: "Affectionate feeling" },
        { word: "PEACEFUL", clue: "Tranquil feeling" },
        { word: "CHEERFUL", clue: "Bright feeling" },
        { word: "CONTENT", clue: "Satisfied feeling" },
        { word: "AMAZED", clue: "Astonished feeling" },
        { word: "RELIEVED", clue: "Unburdened feeling" }
    ],
    
    space: [
        { word: "SUN", clue: "Our star" },
        { word: "MOON", clue: "Earth's satellite" },
        { word: "EARTH", clue: "Our planet" },
        { word: "MARS", clue: "Red planet" },
        { word: "VENUS", clue: "Bright planet" },
        { word: "JUPITER", clue: "Largest planet" },
        { word: "SATURN", clue: "Ringed planet" },
        { word: "URANUS", clue: "Ice giant planet" },
        { word: "NEPTUNE", clue: "Blue planet" },
        { word: "MERCURY", clue: "Closest planet" },
        { word: "STAR", clue: "Burning gas ball" },
        { word: "PLANET", clue: "Orbiting body" },
        { word: "GALAXY", clue: "Star collection" },
        { word: "UNIVERSE", clue: "Everything that exists" },
        { word: "COMET", clue: "Icy space rock" },
        { word: "ASTEROID", clue: "Rocky space object" },
        { word: "METEOR", clue: "Shooting star" },
        { word: "ROCKET", clue: "Space vehicle" },
        { word: "SATELLITE", clue: "Orbiting device" },
        { word: "ASTRONAUT", clue: "Space traveler" },
        { word: "TELESCOPE", clue: "Space viewing tool" },
        { word: "ORBIT", clue: "Circular path" },
        { word: "GRAVITY", clue: "Pulling force" },
        { word: "NEBULA", clue: "Space cloud" },
        { word: "BLACKHOLE", clue: "Space vacuum" },
        { word: "CONSTELLATION", clue: "Star pattern" },
        { word: "MILKYWAY", clue: "Our galaxy" },
        { word: "SPACECRAFT", clue: "Space vessel" },
        { word: "SPACESUIT", clue: "Astronaut clothing" },
        { word: "LAUNCH", clue: "Space takeoff" }
    ],
    
    holidays: [
        { word: "CHRISTMAS", clue: "December celebration" },
        { word: "HALLOWEEN", clue: "October costume day" },
        { word: "EASTER", clue: "Spring egg day" },
        { word: "THANKSGIVING", clue: "November gratitude day" },
        { word: "NEWYEAR", clue: "January first" },
        { word: "BIRTHDAY", clue: "Personal celebration" },
        { word: "VALENTINE", clue: "Love day" },
        { word: "MOTHERS", clue: "Mom appreciation day" },
        { word: "FATHERS", clue: "Dad appreciation day" },
        { word: "MEMORIAL", clue: "Military remembrance" },
        { word: "LABOR", clue: "Worker appreciation" },
        { word: "INDEPENDENCE", clue: "Freedom celebration" },
        { word: "VETERANS", clue: "Service member honor" },
        { word: "MARTIN", clue: "Civil rights leader day" },
        { word: "PRESIDENTS", clue: "Leader celebration" },
        { word: "COLUMBUS", clue: "Explorer day" },
        { word: "HANUKKAH", clue: "Festival of lights" },
        { word: "KWANZAA", clue: "African-American celebration" },
        { word: "PASSOVER", clue: "Jewish spring holiday" },
        { word: "RAMADAN", clue: "Islamic holy month" },
        { word: "DIWALI", clue: "Hindu light festival" },
        { word: "CHINESE", clue: "Asian new year" },
        { word: "CINCO", clue: "Mexican celebration" },
        { word: "PATRICK", clue: "Irish saint day" },
        { word: "APRIL", clue: "Fool's day" },
        { word: "EARTH", clue: "Environmental day" },
        { word: "GRADUATION", clue: "Achievement celebration" },
        { word: "WEDDING", clue: "Marriage celebration" },
        { word: "ANNIVERSARY", clue: "Yearly remembrance" },
        { word: "PARTY", clue: "Fun gathering" }
    ],
    
    money: [
        { word: "DOLLAR", clue: "US currency unit" },
        { word: "CENT", clue: "Penny value" },
        { word: "COIN", clue: "Metal money" },
        { word: "BILL", clue: "Paper money" },
        { word: "CASH", clue: "Physical money" },
        { word: "BANK", clue: "Money institution" },
        { word: "CREDIT", clue: "Borrowed money" },
        { word: "DEBIT", clue: "Account money" },
        { word: "LOAN", clue: "Borrowed funds" },
        { word: "SAVE", clue: "Keep money" },
        { word: "SPEND", clue: "Use money" },
        { word: "BUDGET", clue: "Money plan" },
        { word: "INCOME", clue: "Money earned" },
        { word: "EXPENSE", clue: "Money spent" },
        { word: "PROFIT", clue: "Money gained" },
        { word: "LOSS", clue: "Money lost" },
        { word: "PRICE", clue: "Cost amount" },
        { word: "SALE", clue: "Reduced price" },
        { word: "DISCOUNT", clue: "Price reduction" },
        { word: "TAX", clue: "Government fee" },
        { word: "INTEREST", clue: "Money charge" },
        { word: "DEPOSIT", clue: "Money placement" },
        { word: "WITHDRAW", clue: "Money removal" },
        { word: "ACCOUNT", clue: "Money record" },
        { word: "BALANCE", clue: "Money amount" },
        { word: "RECEIPT", clue: "Purchase proof" },
        { word: "WALLET", clue: "Money holder" },
        { word: "PURSE", clue: "Money bag" },
        { word: "CHANGE", clue: "Money returned" },
        { word: "PENNY", clue: "One cent coin" }
    ],
    
    ocean: [
        { word: "WAVE", clue: "Water motion" },
        { word: "TIDE", clue: "Water level change" },
        { word: "BEACH", clue: "Shore area" },
        { word: "SAND", clue: "Beach material" },
        { word: "SHELL", clue: "Sea creature home" },
        { word: "CRAB", clue: "Sideways walking creature" },
        { word: "FISH", clue: "Swimming creature" },
        { word: "WHALE", clue: "Largest sea mammal" },
        { word: "DOLPHIN", clue: "Intelligent sea mammal" },
        { word: "SHARK", clue: "Predator fish" },
        { word: "OCTOPUS", clue: "Eight-armed creature" },
        { word: "JELLYFISH", clue: "Transparent sea creature" },
        { word: "SEAHORSE", clue: "Horse-shaped fish" },
        { word: "STARFISH", clue: "Star-shaped creature" },
        { word: "CORAL", clue: "Reef building organism" },
        { word: "SEAWEED", clue: "Ocean plant" },
        { word: "BOAT", clue: "Water vessel" },
        { word: "SHIP", clue: "Large water vessel" },
        { word: "SAIL", clue: "Wind catcher" },
        { word: "ANCHOR", clue: "Ship stopper" },
        { word: "LIGHTHOUSE", clue: "Navigation beacon" },
        { word: "PIER", clue: "Water platform" },
        { word: "HARBOR", clue: "Ship shelter" },
        { word: "ISLAND", clue: "Land in water" },
        { word: "SUBMARINE", clue: "Underwater vessel" },
        { word: "TREASURE", clue: "Hidden riches" },
        { word: "SAILOR", clue: "Ship worker" },
        { word: "CAPTAIN", clue: "Ship leader" },
        { word: "COMPASS", clue: "Direction finder" },
        { word: "STORM", clue: "Rough weather" }
    ],
    
    time: [
        { word: "HOUR", clue: "Time unit" },
        { word: "MINUTE", clue: "Sixty seconds" },
        { word: "SECOND", clue: "Time instant" },
        { word: "DAY", clue: "Twenty-four hours" },
        { word: "WEEK", clue: "Seven days" },
        { word: "MONTH", clue: "Calendar division" },
        { word: "YEAR", clue: "Twelve months" },
        { word: "MORNING", clue: "Early day" },
        { word: "AFTERNOON", clue: "Mid day" },
        { word: "EVENING", clue: "Late day" },
        { word: "NIGHT", clue: "Dark time" },
        { word: "DAWN", clue: "First light" },
        { word: "DUSK", clue: "Last light" },
        { word: "MIDNIGHT", clue: "Twelve at night" },
        { word: "NOON", clue: "Twelve at day" },
        { word: "SUNRISE", clue: "Morning light" },
        { word: "SUNSET", clue: "Evening light" },
        { word: "CLOCK", clue: "Time device" },
        { word: "WATCH", clue: "Wrist timepiece" },
        { word: "CALENDAR", clue: "Date tracker" },
        { word: "SCHEDULE", clue: "Time plan" },
        { word: "DEADLINE", clue: "Time limit" },
        { word: "EARLY", clue: "Before time" },
        { word: "LATE", clue: "After time" },
        { word: "PUNCTUAL", clue: "On time" },
        { word: "PAST", clue: "Before now" },
        { word: "PRESENT", clue: "Right now" },
        { word: "FUTURE", clue: "After now" },
        { word: "CENTURY", clue: "Hundred years" },
        { word: "DECADE", clue: "Ten years" }
    ],
    
    movies: [
        { word: "FILM", clue: "Motion picture" },
        { word: "MOVIE", clue: "Cinema show" },
        { word: "ACTOR", clue: "Movie performer" },
        { word: "ACTRESS", clue: "Female performer" },
        { word: "DIRECTOR", clue: "Movie maker" },
        { word: "SCRIPT", clue: "Movie text" },
        { word: "SCENE", clue: "Movie part" },
        { word: "CAMERA", clue: "Recording device" },
        { word: "SCREEN", clue: "Display surface" },
        { word: "THEATER", clue: "Movie venue" },
        { word: "TICKET", clue: "Entry pass" },
        { word: "POPCORN", clue: "Movie snack" },
        { word: "COMEDY", clue: "Funny movie" },
        { word: "DRAMA", clue: "Serious movie" },
        { word: "ACTION", clue: "Exciting movie" },
        { word: "HORROR", clue: "Scary movie" },
        { word: "ROMANCE", clue: "Love movie" },
        { word: "FANTASY", clue: "Magical movie" },
        { word: "WESTERN", clue: "Cowboy movie" },
        { word: "CARTOON", clue: "Animated movie" },
        { word: "DOCUMENTARY", clue: "Factual movie" },
        { word: "SEQUEL", clue: "Follow-up movie" },
        { word: "PREMIERE", clue: "First showing" },
        { word: "TRAILER", clue: "Movie preview" },
        { word: "Oscar", clue: "Movie award" },
        { word: "HOLLYWOOD", clue: "Movie capital" },
        { word: "BLOCKBUSTER", clue: "Popular movie" },
        { word: "CLASSIC", clue: "Timeless movie" },
        { word: "CINEMA", clue: "Movie art" },
        { word: "STUDIO", clue: "Movie company" }
    ],
    
    books: [
        { word: "BOOK", clue: "Reading material" },
        { word: "PAGE", clue: "Book sheet" },
        { word: "CHAPTER", clue: "Book section" },
        { word: "STORY", clue: "Narrative tale" },
        { word: "NOVEL", clue: "Long fiction" },
        { word: "POEM", clue: "Verse writing" },
        { word: "AUTHOR", clue: "Book writer" },
        { word: "READER", clue: "Book consumer" },
        { word: "LIBRARY", clue: "Book collection" },
        { word: "BOOKSTORE", clue: "Book shop" },
        { word: "FICTION", clue: "Made-up story" },
        { word: "MYSTERY", clue: "Puzzle story" },
        { word: "ROMANCE", clue: "Love story" },
        { word: "FANTASY", clue: "Magical story" },
        { word: "BIOGRAPHY", clue: "Life story" },
        { word: "HISTORY", clue: "Past events" },
        { word: "SCIENCE", clue: "Knowledge study" },
        { word: "COOKBOOK", clue: "Recipe collection" },
        { word: "TEXTBOOK", clue: "Study material" },
        { word: "MAGAZINE", clue: "Periodic publication" },
        { word: "NEWSPAPER", clue: "Daily publication" },
        { word: "JOURNAL", clue: "Personal writing" },
        { word: "DIARY", clue: "Daily record" },
        { word: "ENCYCLOPEDIA", clue: "Knowledge collection" },
        { word: "DICTIONARY", clue: "Word reference" },
        { word: "ATLAS", clue: "Map collection" },
        { word: "COMIC", clue: "Picture story" },
        { word: "MANUAL", clue: "Instruction book" },
        { word: "CATALOG", clue: "Item list" },
        { word: "BESTSELLER", clue: "Popular book" }
    ],
    
    shapes: [
        { word: "CIRCLE", clue: "Round shape" },
        { word: "SQUARE", clue: "Four equal sides" },
        { word: "TRIANGLE", clue: "Three-sided shape" },
        { word: "RECTANGLE", clue: "Four-sided shape" },
        { word: "OVAL", clue: "Egg-like shape" },
        { word: "DIAMOND", clue: "Pointed shape" },
        { word: "STAR", clue: "Pointed shape" },
        { word: "HEART", clue: "Love shape" },
        { word: "ARROW", clue: "Pointing shape" },
        { word: "CROSS", clue: "Plus shape" },
        { word: "HEXAGON", clue: "Six-sided shape" },
        { word: "OCTAGON", clue: "Eight-sided shape" },
        { word: "PENTAGON", clue: "Five-sided shape" },
        { word: "CUBE", clue: "Box shape" },
        { word: "SPHERE", clue: "Ball shape" },
        { word: "CYLINDER", clue: "Tube shape" },
        { word: "CONE", clue: "Ice cream shape" },
        { word: "PYRAMID", clue: "Egyptian shape" },
        { word: "CRESCENT", clue: "Moon shape" },
        { word: "SPIRAL", clue: "Coiled shape" },
        { word: "ZIGZAG", clue: "Sharp turns" },
        { word: "CURVE", clue: "Bent line" },
        { word: "ANGLE", clue: "Corner shape" },
        { word: "LINE", clue: "Straight mark" },
        { word: "DOT", clue: "Small circle" },
        { word: "POINT", clue: "Sharp end" },
        { word: "EDGE", clue: "Shape border" },
        { word: "CORNER", clue: "Shape meeting" },
        { word: "SIDE", clue: "Shape boundary" },
        { word: "CENTER", clue: "Shape middle" }
    ],
    
    numbers: [
        { word: "ONE", clue: "First number" },
        { word: "TWO", clue: "Second number" },
        { word: "THREE", clue: "Third number" },
        { word: "FOUR", clue: "Fourth number" },
        { word: "FIVE", clue: "Fifth number" },
        { word: "SIX", clue: "Sixth number" },
        { word: "SEVEN", clue: "Seventh number" },
        { word: "EIGHT", clue: "Eighth number" },
        { word: "NINE", clue: "Ninth number" },
        { word: "TEN", clue: "Tenth number" },
        { word: "ELEVEN", clue: "Eleventh number" },
        { word: "TWELVE", clue: "Twelfth number" },
        { word: "TWENTY", clue: "Two tens" },
        { word: "THIRTY", clue: "Three tens" },
        { word: "FORTY", clue: "Four tens" },
        { word: "FIFTY", clue: "Five tens" },
        { word: "SIXTY", clue: "Six tens" },
        { word: "SEVENTY", clue: "Seven tens" },
        { word: "EIGHTY", clue: "Eight tens" },
        { word: "NINETY", clue: "Nine tens" },
        { word: "HUNDRED", clue: "Ten tens" },
        { word: "THOUSAND", clue: "Ten hundreds" },
        { word: "MILLION", clue: "Thousand thousands" },
        { word: "BILLION", clue: "Thousand millions" },
        { word: "FIRST", clue: "Number one position" },
        { word: "SECOND", clue: "Number two position" },
        { word: "THIRD", clue: "Number three position" },
        { word: "FOURTH", clue: "Number four position" },
        { word: "FIFTH", clue: "Number five position" },
        { word: "LAST", clue: "Final position" }
    ],
    
    computers: [
        { word: "MOUSE", clue: "Computer pointer" },
        { word: "KEYBOARD", clue: "Input device" },
        { word: "SCREEN", clue: "Display device" },
        { word: "PRINTER", clue: "Output device" },
        { word: "SPEAKER", clue: "Audio output" },
        { word: "WEBCAM", clue: "Video input" },
        { word: "LAPTOP", clue: "Portable computer" },
        { word: "TABLET", clue: "Touch computer" },
        { word: "PHONE", clue: "Mobile device" },
        { word: "ROUTER", clue: "Network device" },
        { word: "CABLE", clue: "Connection wire" },
        { word: "BATTERY", clue: "Power source" },
        { word: "CHARGER", clue: "Power device" },
        { word: "MEMORY", clue: "Storage space" },
        { word: "DISK", clue: "Storage device" },
        { word: "FILE", clue: "Data container" },
        { word: "FOLDER", clue: "File organizer" },
        { word: "PROGRAM", clue: "Software application" },
        { word: "GAME", clue: "Entertainment software" },
        { word: "INTERNET", clue: "Global network" },
        { word: "WEBSITE", clue: "Online location" },
        { word: "EMAIL", clue: "Electronic message" },
        { word: "SEARCH", clue: "Information finding" },
        { word: "DOWNLOAD", clue: "Data receiving" },
        { word: "UPLOAD", clue: "Data sending" },
        { word: "BACKUP", clue: "Data copy" },
        { word: "VIRUS", clue: "Harmful software" },
        { word: "PASSWORD", clue: "Access code" },
        { word: "USERNAME", clue: "User identifier" },
        { word: "LOGIN", clue: "Access process" }
    ],
    
    insects: [
        { word: "ANT", clue: "Colony insect" },
        { word: "BEE", clue: "Honey maker" },
        { word: "FLY", clue: "Buzzing pest" },
        { word: "MOTH", clue: "Night butterfly" },
        { word: "WASP", clue: "Stinging insect" },
        { word: "FLEA", clue: "Jumping pest" },
        { word: "TICK", clue: "Blood sucker" },
        { word: "MITE", clue: "Tiny pest" },
        { word: "GNAT", clue: "Small fly" },
        { word: "APHID", clue: "Plant pest" },
        { word: "BEETLE", clue: "Hard shell insect" },
        { word: "SPIDER", clue: "Web maker" },
        { word: "CRICKET", clue: "Chirping insect" },
        { word: "MOSQUITO", clue: "Biting pest" },
        { word: "BUTTERFLY", clue: "Colorful flyer" },
        { word: "DRAGONFLY", clue: "Pond flyer" },
        { word: "LADYBUG", clue: "Spotted beetle" },
        { word: "FIREFLY", clue: "Glowing insect" },
        { word: "GRASSHOPPER", clue: "Jumping insect" },
        { word: "CATERPILLAR", clue: "Butterfly baby" },
        { word: "TERMITE", clue: "Wood eater" },
        { word: "ROACH", clue: "Kitchen pest" },
        { word: "LOCUST", clue: "Swarm insect" },
        { word: "CICADA", clue: "Loud insect" },
        { word: "MANTIS", clue: "Praying insect" },
        { word: "HORNET", clue: "Large wasp" },
        { word: "WEEVIL", clue: "Grain pest" },
        { word: "EARWIG", clue: "Pincer insect" },
        { word: "THRIP", clue: "Tiny pest" },
        { word: "SCALE", clue: "Plant pest" }
    ],
    
    fish: [
        { word: "BASS", clue: "Game fish" },
        { word: "TROUT", clue: "Stream fish" },
        { word: "SALMON", clue: "Pink fish" },
        { word: "TUNA", clue: "Large fish" },
        { word: "SHARK", clue: "Predator fish" },
        { word: "GOLDFISH", clue: "Pet fish" },
        { word: "CATFISH", clue: "Whiskered fish" },
        { word: "SUNFISH", clue: "Round fish" },
        { word: "PERCH", clue: "Spiny fish" },
        { word: "PIKE", clue: "Long fish" },
        { word: "CARP", clue: "Pond fish" },
        { word: "COD", clue: "White fish" },
        { word: "HALIBUT", clue: "Flat fish" },
        { word: "FLOUNDER", clue: "Bottom fish" },
        { word: "SOLE", clue: "Flat fish" },
        { word: "MACKEREL", clue: "Striped fish" },
        { word: "HERRING", clue: "School fish" },
        { word: "SARDINE", clue: "Small fish" },
        { word: "ANCHOVY", clue: "Tiny fish" },
        { word: "SWORDFISH", clue: "Bill fish" },
        { word: "MARLIN", clue: "Sport fish" },
        { word: "BARRACUDA", clue: "Fast fish" },
        { word: "SNAPPER", clue: "Reef fish" },
        { word: "GROUPER", clue: "Large fish" },
        { word: "ANGELFISH", clue: "Pretty fish" },
        { word: "CLOWNFISH", clue: "Orange fish" },
        { word: "SEAHORSE", clue: "Horse fish" },
        { word: "STINGRAY", clue: "Flat fish" },
        { word: "ELECTRIC", clue: "Shocking fish" },
        { word: "PUFFERFISH", clue: "Inflating fish" }
    ],
    
    birds: [
        { word: "ROBIN", clue: "Red breast bird" },
        { word: "EAGLE", clue: "Majestic bird" },
        { word: "HAWK", clue: "Hunting bird" },
        { word: "OWL", clue: "Night bird" },
        { word: "CROW", clue: "Black bird" },
        { word: "DUCK", clue: "Water bird" },
        { word: "GOOSE", clue: "Large water bird" },
        { word: "SWAN", clue: "Graceful bird" },
        { word: "CHICKEN", clue: "Farm bird" },
        { word: "TURKEY", clue: "Thanksgiving bird" },
        { word: "PEACOCK", clue: "Fancy tail bird" },
        { word: "PARROT", clue: "Talking bird" },
        { word: "CANARY", clue: "Yellow singing bird" },
        { word: "CARDINAL", clue: "Red bird" },
        { word: "BLUEJAY", clue: "Blue bird" },
        { word: "SPARROW", clue: "Small bird" },
        { word: "PIGEON", clue: "City bird" },
        { word: "SEAGULL", clue: "Beach bird" },
        { word: "PELICAN", clue: "Pouch bird" },
        { word: "FLAMINGO", clue: "Pink bird" },
        { word: "PENGUIN", clue: "Tuxedo bird" },
        { word: "OSTRICH", clue: "Tall bird" },
        { word: "HUMMINGBIRD", clue: "Tiny fast bird" },
        { word: "WOODPECKER", clue: "Tree tapping bird" },
        { word: "KINGFISHER", clue: "Diving bird" },
        { word: "SWALLOW", clue: "Fast bird" },
        { word: "STARLING", clue: "Flock bird" },
        { word: "THRUSH", clue: "Song bird" },
        { word: "WREN", clue: "Tiny bird" },
        { word: "FINCH", clue: "Seed bird" }
    ],
    
    planets: [
        { word: "MERCURY", clue: "Closest planet" },
        { word: "VENUS", clue: "Hottest planet" },
        { word: "EARTH", clue: "Our home planet" },
        { word: "MARS", clue: "Red planet" },
        { word: "JUPITER", clue: "Giant planet" },
        { word: "SATURN", clue: "Ringed planet" },
        { word: "URANUS", clue: "Tilted planet" },
        { word: "NEPTUNE", clue: "Windy planet" },
        { word: "PLUTO", clue: "Dwarf planet" },
        { word: "MOON", clue: "Earth's companion" },
        { word: "SUN", clue: "Our star" },
        { word: "SOLAR", clue: "Sun system" },
        { word: "ORBIT", clue: "Circular path" },
        { word: "GRAVITY", clue: "Pulling force" },
        { word: "ASTEROID", clue: "Space rock" },
        { word: "COMET", clue: "Icy visitor" },
        { word: "METEOR", clue: "Falling star" },
        { word: "GALAXY", clue: "Star group" },
        { word: "UNIVERSE", clue: "All space" },
        { word: "CRATER", clue: "Impact hole" },
        { word: "ATMOSPHERE", clue: "Air layer" },
        { word: "TELESCOPE", clue: "Star viewer" },
        { word: "ROCKET", clue: "Space ship" },
        { word: "SATELLITE", clue: "Orbiting object" },
        { word: "ASTRONAUT", clue: "Space traveler" },
        { word: "SPACE", clue: "Void above" },
        { word: "STAR", clue: "Bright light" },
        { word: "NEBULA", clue: "Star cloud" },
        { word: "BLACKHOLE", clue: "Space vacuum" },
        { word: "LIGHTYEAR", clue: "Distance unit" }
    ],
    
    flowers: [
        { word: "ROSE", clue: "Thorny flower" },
        { word: "LILY", clue: "Pond flower" },
        { word: "TULIP", clue: "Spring bulb" },
        { word: "DAISY", clue: "White petals" },
        { word: "ORCHID", clue: "Exotic flower" },
        { word: "IRIS", clue: "Flag flower" },
        { word: "PANSY", clue: "Face flower" },
        { word: "PEONY", clue: "Fluffy flower" },
        { word: "POPPY", clue: "Red field flower" },
        { word: "VIOLET", clue: "Purple flower" },
        { word: "JASMINE", clue: "Fragrant flower" },
        { word: "GARDENIA", clue: "White flower" },
        { word: "CAMELLIA", clue: "Tea flower" },
        { word: "BEGONIA", clue: "Waxy flower" },
        { word: "PETUNIA", clue: "Trumpet flower" },
        { word: "MARIGOLD", clue: "Orange flower" },
        { word: "ZINNIA", clue: "Bright flower" },
        { word: "COSMOS", clue: "Delicate flower" },
        { word: "DAHLIA", clue: "Dinner plate flower" },
        { word: "GLADIOLUS", clue: "Sword flower" },
        { word: "CARNATION", clue: "Ruffled flower" },
        { word: "CHRYSANTHEMUM", clue: "Fall flower" },
        { word: "SUNFLOWER", clue: "Giant yellow flower" },
        { word: "DAFFODIL", clue: "Spring trumpet" },
        { word: "HYACINTH", clue: "Fragrant spike" },
        { word: "CROCUS", clue: "Early spring flower" },
        { word: "AZALEA", clue: "Shrub flower" },
        { word: "RHODODENDRON", clue: "Mountain flower" },
        { word: "LILAC", clue: "Purple cluster" },
        { word: "FORSYTHIA", clue: "Yellow branch" }
    ],
    
    gems: [
        { word: "DIAMOND", clue: "Hardest gem" },
        { word: "RUBY", clue: "Red gem" },
        { word: "EMERALD", clue: "Green gem" },
        { word: "SAPPHIRE", clue: "Blue gem" },
        { word: "PEARL", clue: "Ocean gem" },
        { word: "OPAL", clue: "Fire gem" },
        { word: "JADE", clue: "Green stone" },
        { word: "AMBER", clue: "Golden resin" },
        { word: "AMETHYST", clue: "Purple quartz" },
        { word: "CITRINE", clue: "Yellow quartz" },
        { word: "GARNET", clue: "Deep red gem" },
        { word: "PERIDOT", clue: "Olive gem" },
        { word: "TOPAZ", clue: "Golden gem" },
        { word: "TURQUOISE", clue: "Blue stone" },
        { word: "ONYX", clue: "Black stone" },
        { word: "AGATE", clue: "Banded stone" },
        { word: "JASPER", clue: "Spotted stone" },
        { word: "QUARTZ", clue: "Clear crystal" },
        { word: "CRYSTAL", clue: "Clear mineral" },
        { word: "JEWEL", clue: "Precious stone" },
        { word: "GOLD", clue: "Precious metal" },
        { word: "SILVER", clue: "Shiny metal" },
        { word: "PLATINUM", clue: "Rare metal" },
        { word: "BRONZE", clue: "Copper alloy" },
        { word: "COPPER", clue: "Red metal" },
        { word: "IRON", clue: "Strong metal" },
        { word: "STEEL", clue: "Iron alloy" },
        { word: "ALUMINUM", clue: "Light metal" },
        { word: "TITANIUM", clue: "Strong light metal" },
        { word: "ZINC", clue: "Coating metal" }
    ],
    
    furniture: [
        { word: "CHAIR", clue: "Seating furniture" },
        { word: "TABLE", clue: "Flat surface" },
        { word: "SOFA", clue: "Soft seating" },
        { word: "BED", clue: "Sleeping furniture" },
        { word: "DESK", clue: "Work surface" },
        { word: "DRESSER", clue: "Clothing storage" },
        { word: "CLOSET", clue: "Storage space" },
        { word: "BOOKSHELF", clue: "Book storage" },
        { word: "CABINET", clue: "Storage unit" },
        { word: "DRAWER", clue: "Sliding storage" },
        { word: "LAMP", clue: "Light source" },
        { word: "MIRROR", clue: "Reflection surface" },
        { word: "CURTAIN", clue: "Window cover" },
        { word: "CARPET", clue: "Floor covering" },
        { word: "PILLOW", clue: "Head rest" },
        { word: "BLANKET", clue: "Bed covering" },
        { word: "MATTRESS", clue: "Bed base" },
        { word: "WARDROBE", clue: "Clothing cabinet" },
        { word: "NIGHTSTAND", clue: "Bedside table" },
        { word: "OTTOMAN", clue: "Foot rest" },
        { word: "RECLINER", clue: "Resting chair" },
        { word: "STOOL", clue: "Backless seat" },
        { word: "BENCH", clue: "Long seat" },
        { word: "COUCH", clue: "Living room seat" },
        { word: "ARMCHAIR", clue: "Single seat" },
        { word: "ROCKING", clue: "Moving chair" },
        { word: "DINING", clue: "Eating table" },
        { word: "COFFEE", clue: "Living room table" },
        { word: "KITCHEN", clue: "Cooking table" },
        { word: "FOLDING", clue: "Portable chair" }
    ]
};

// Make puzzles globally available
window.puzzles = puzzles;