const puzzles = {
    animals: [
        { word: "ELEPHANT", clue: "Largest land animal" },
        { word: "TIGER", clue: "Striped big cat" },
        { word: "DOLPHIN", clue: "Intelligent marine mammal" },
        { word: "EAGLE", clue: "National bird of America" },
        { word: "BEAR", clue: "Large forest mammal" },
        { word: "WOLF", clue: "Pack hunting canine" },
        { word: "ZEBRA", clue: "Striped African horse" },
        { word: "GIRAFFE", clue: "Tallest animal in the world" },
        { word: "PENGUIN", clue: "Flightless Antarctic bird" },
        { word: "KANGAROO", clue: "Hopping Australian marsupial" },
        { word: "LION", clue: "King of the jungle" },
        { word: "MONKEY", clue: "Primate that swings from trees" },
        { word: "RABBIT", clue: "Hopping garden visitor" },
        { word: "DEER", clue: "Antlered forest animal" },
        { word: "SHARK", clue: "Ocean predator with sharp teeth" },
        { word: "WHALE", clue: "Largest mammal in the ocean" },
        { word: "HORSE", clue: "Domesticated riding animal" },
        { word: "COW", clue: "Farm animal that gives milk" },
        { word: "PIG", clue: "Farm animal that rolls in mud" },
        { word: "CHICKEN", clue: "Farm bird that lays eggs" },
        { word: "DOG", clue: "Man's best friend" },
        { word: "CAT", clue: "Independent house pet" },
        { word: "FISH", clue: "Water-dwelling creature" },
        { word: "BIRD", clue: "Flying creature with feathers" },
        { word: "SNAKE", clue: "Slithering reptile" },
        { word: "TURTLE", clue: "Reptile with a shell" },
        { word: "FROG", clue: "Amphibian that croaks" },
        { word: "SPIDER", clue: "Eight-legged web spinner" },
        { word: "ANT", clue: "Hard-working insect" },
        { word: "BEE", clue: "Buzzing pollinator" }
    ],
    
    plants: [
        { word: "ROSE", clue: "Thorny romantic flower" },
        { word: "TULIP", clue: "Dutch spring bulb flower" },
        { word: "CACTUS", clue: "Desert plant with spines" },
        { word: "BAMBOO", clue: "Fast-growing Asian grass" },
        { word: "ORCHID", clue: "Exotic tropical flower" },
        { word: "FERN", clue: "Ancient spore-bearing plant" },
        { word: "MAPLE", clue: "Tree known for syrup" },
        { word: "LAVENDER", clue: "Purple fragrant herb" },
        { word: "SUNFLOWER", clue: "Tall yellow flower that tracks the sun" },
        { word: "DAISY", clue: "White petaled common flower" },
        { word: "LILY", clue: "Elegant pond flower" },
        { word: "IRIS", clue: "Colorful spring flower" },
        { word: "PINE", clue: "Evergreen tree with needles" },
        { word: "OAK", clue: "Strong tree with acorns" },
        { word: "VINE", clue: "Climbing plant" },
        { word: "MOSS", clue: "Soft green ground cover" },
        { word: "GRASS", clue: "Lawn covering" },
        { word: "HERB", clue: "Cooking plant" },
        { word: "SEED", clue: "Plant beginning" },
        { word: "ROOT", clue: "Underground plant part" },
        { word: "LEAF", clue: "Green plant part" },
        { word: "STEM", clue: "Plant support structure" },
        { word: "TREE", clue: "Large woody plant" },
        { word: "BUSH", clue: "Small woody plant" },
        { word: "FLOWER", clue: "Colorful plant bloom" },
        { word: "PETAL", clue: "Flower part" },
        { word: "THORN", clue: "Sharp plant protection" },
        { word: "BRANCH", clue: "Tree limb" },
        { word: "BARK", clue: "Tree skin" },
        { word: "GARDEN", clue: "Cultivated plant area" }
    ],
    
    computers: [
        { word: "KEYBOARD", clue: "Input device with keys" },
        { word: "MONITOR", clue: "Computer display screen" },
        { word: "MOUSE", clue: "Pointing device for computers" },
        { word: "PIXEL", clue: "Smallest unit of a digital image" },
        { word: "BROWSER", clue: "Software for viewing websites" },
        { word: "SERVER", clue: "Computer that provides services" },
        { word: "CODING", clue: "Writing computer programs" },
        { word: "VIRUS", clue: "Malicious computer program" },
        { word: "BACKUP", clue: "Copy of data for safety" },
        { word: "WEBSITE", clue: "Collection of web pages" },
        { word: "EMAIL", clue: "Electronic mail system" },
        { word: "INTERNET", clue: "Global computer network" },
        { word: "SOFTWARE", clue: "Computer programs" },
        { word: "HARDWARE", clue: "Physical computer parts" },
        { word: "MEMORY", clue: "Computer storage space" },
        { word: "PRINTER", clue: "Device that prints documents" },
        { word: "SCANNER", clue: "Device that digitizes documents" },
        { word: "NETWORK", clue: "Connected computers" },
        { word: "DATABASE", clue: "Organized data collection" },
        { word: "ALGORITHM", clue: "Problem-solving procedure" },
        { word: "PROGRAM", clue: "Computer instructions" },
        { word: "FILE", clue: "Digital document" },
        { word: "FOLDER", clue: "File organizer" },
        { word: "SCREEN", clue: "Display surface" },
        { word: "BUTTON", clue: "Clickable interface element" },
        { word: "WINDOW", clue: "Application display area" },
        { word: "MENU", clue: "List of options" },
        { word: "ICON", clue: "Small graphic symbol" },
        { word: "CURSOR", clue: "Screen pointer" },
        { word: "DESKTOP", clue: "Computer main screen" }
    ],
    
    bugs: [
        { word: "BUTTERFLY", clue: "Colorful winged insect" },
        { word: "SPIDER", clue: "Eight-legged web spinner" },
        { word: "BEETLE", clue: "Hard-shelled insect" },
        { word: "CRICKET", clue: "Chirping jumping insect" },
        { word: "DRAGONFLY", clue: "Fast-flying pond insect" },
        { word: "LADYBUG", clue: "Red spotted beneficial beetle" },
        { word: "MOSQUITO", clue: "Blood-sucking flying pest" },
        { word: "FIREFLY", clue: "Bioluminescent evening insect" },
        { word: "CATERPILLAR", clue: "Butterfly larva stage" },
        { word: "GRASSHOPPER", clue: "Green jumping field insect" },
        { word: "ANT", clue: "Colony-living worker insect" },
        { word: "BEE", clue: "Honey-making pollinator" },
        { word: "WASP", clue: "Stinging flying insect" },
        { word: "MOTH", clue: "Night-flying winged insect" },
        { word: "FLY", clue: "Common buzzing pest" },
        { word: "FLEA", clue: "Jumping parasitic insect" },
        { word: "TICK", clue: "Blood-sucking arachnid" },
        { word: "MITE", clue: "Tiny arachnid" },
        { word: "ROACH", clue: "Resilient household pest" },
        { word: "TERMITE", clue: "Wood-eating insect" },
        { word: "APHID", clue: "Plant-sucking pest" },
        { word: "LOCUST", clue: "Swarming grasshopper" },
        { word: "CICADA", clue: "Loud summer insect" },
        { word: "MANTIS", clue: "Praying predator insect" },
        { word: "HORNET", clue: "Large stinging wasp" },
        { word: "GNAT", clue: "Tiny flying pest" },
        { word: "WEEVIL", clue: "Grain-eating beetle" },
        { word: "EARWIG", clue: "Insect with pincers" },
        { word: "THRIP", clue: "Tiny plant pest" },
        { word: "SCALE", clue: "Plant-sucking insect" }
    ],
    
    fish: [
        { word: "SALMON", clue: "Pink fish that swims upstream" },
        { word: "SHARK", clue: "Predatory ocean fish" },
        { word: "TUNA", clue: "Large commercial fish" },
        { word: "GOLDFISH", clue: "Popular orange pet fish" },
        { word: "TROUT", clue: "Freshwater sport fish" },
        { word: "BASS", clue: "Popular game fish" },
        { word: "SWORDFISH", clue: "Fish with a long pointed bill" },
        { word: "ANGELFISH", clue: "Tropical aquarium fish" },
        { word: "CATFISH", clue: "Bottom-dwelling whiskered fish" },
        { word: "SEAHORSE", clue: "Horse-shaped marine fish" },
        { word: "COD", clue: "White meat ocean fish" },
        { word: "HALIBUT", clue: "Large flatfish" },
        { word: "MACKEREL", clue: "Striped ocean fish" },
        { word: "HERRING", clue: "Small schooling fish" },
        { word: "ANCHOVY", clue: "Tiny salty fish" },
        { word: "SARDINE", clue: "Small canned fish" },
        { word: "FLOUNDER", clue: "Flat bottom fish" },
        { word: "SOLE", clue: "Flatfish with both eyes on one side" },
        { word: "PIKE", clue: "Freshwater predator fish" },
        { word: "PERCH", clue: "Spiny-finned freshwater fish" },
        { word: "CARP", clue: "Large freshwater fish" },
        { word: "EEL", clue: "Snake-like fish" },
        { word: "RAY", clue: "Flat cartilaginous fish" },
        { word: "MANTA", clue: "Giant ray species" },
        { word: "BARRACUDA", clue: "Aggressive tropical fish" },
        { word: "GROUPER", clue: "Large reef fish" },
        { word: "SNAPPER", clue: "Colorful tropical fish" },
        { word: "MARLIN", clue: "Large billfish" },
        { word: "MAHI", clue: "Colorful dolphin fish" },
        { word: "WAHOO", clue: "Fast swimming game fish" }
    ]
};

// Make puzzles globally available
window.puzzles = puzzles;